### ISSUE TITLE
SSWLinkAuditor - reported broken links - https://www.ssw.com.au/people/mehmet-ozdemir/

### ISSUE THREAD

**Issue by nvhoanganh** [SSWConsulting/People#137]
sourceUri | targetUri | lineNumber | linePosition | status | statusDetail
-- | -- | -- | -- | -- | --
https://www.ssw.com.au/people/mehmet-ozdemir/ | http://macanz.com/ | 78 | 12 | Failure | NotFound
https://www.ssw.com.au/people/mehmet-ozdemir/ | http://www.turbomeca.com/ | 84 | 12 | Failure | InvalidRemoteName
https://www.ssw.com.au/people/mehmet-ozdemir/ | https://carnival.com.au/ | 75 | 12 | Failure | TimeOut
https://www.ssw.com.au/people/mehmet-ozdemir/ | https://ssw.com.au/people/people/mehmet-ozdemir | 1 | 714439 | Failure | NotFound
https://www.ssw.com.au/people/mehmet-ozdemir/ | https://www.ssw.com.au/manifest.json | 1 | 714542 | Failure | NotFound
https://www.ssw.com.au/people/mehmet-ozdemir/ | https://www.ssw.com.au/ssw/include/pigeon/img/apple-touch-icon-167x167.png | 1 | 715643 | Failure | NotFound

**Comment by patriciabarrosssw** [comment]
Broken links were fixed
