### ISSUE TITLE
SSWLinkAuditor - reported broken links - https://www.ssw.com.au/people/jk

### ISSUE THREAD

**Issue by nvhoanganh** [SSWConsulting/People#139]
sourceUri | targetUri | lineNumber | linePosition | status | statusDetail
-- | -- | -- | -- | -- | --
https://www.ssw.com.au/people/jk/ | https://sswsophie.com/sophie-bot | 465 | 203 | Failure | NotFound

**Comment by SebastienBoissiere** [comment]
Fixed, I changed the link on JK's profile
