### ISSUE TITLE
Chris Clement - improve

### ISSUE THREAD

**Issue by adamcogan** [SSWConsulting/People#83]
Hey Chris @christoment 
1. Can you add some bold to highlight some skills - like the profile @JeanThirion 
2. Add some logos - like Jean too
3. Have a look at another profile like Williams for any other ideas @william-liebenberg 

-a

**Comment by christoment** [comment]
Hi @adamcogan - done :) 

@SebastienBoissiere could you help me close this ticket? Thank you 😊
